common: &common
  adapter: mysql2
  encoding: utf8
  reconnect: true
  pool: 5
  username: root
  password:
  host: '127.0.0.1'

development:
  <<: *common
  database: app_development

test:
  <<: *common
  database: app_test

production:
  database: app_production
  adapter: postgresql
  encoding: unicode
  pool: 5
  password:
